language: cpp
sudo: required
dist: trusty

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/boost
    - ${TRAVIS_BUILD_DIR}/deps/cmake

matrix:
  include:

    # 1/ Linux Clang Builds
    - os: linux
      compiler: clang
      addons: &clang39
        apt:
          sources: ['llvm-toolchain-precise-3.9', 'ubuntu-toolchain-r-test']
          packages: ['clang-3.9', 'g++-6']
      env: COMPILER='clang++-3.9'

    # 2/ Linux GCC Builds
    - os: linux
      compiler: gcc
      addons: &gcc6
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env: COMPILER='g++-6'


install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - BOOST_DIR=${DEPS_DIR}/boost
  - BOOST_URL="http://github.com/boostorg/boost.git"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 60;
      sudo update-alternatives --config gcc;
      sudo update-alternatives --config g++;
      travis_retry git clone --depth 1 --recursive ${BOOST_URL} ${BOOST_DIR} || exit 1
      (cd ${BOOST_DIR} && ./bootstrap.sh && ./b2 --with-test install) || exit 1
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      which cmake || brew install cmake
      brew install boost
    fi
  - cd ${TRAVIS_BUILD_DIR}

before_script: export CXX=${COMPILER}

script:
  - ./scripts/build.py --tests
