# Modify this line to test Travis Integration ....
sudo: false

language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      services:
        - docker
      install:
        - docker build . -t travis-ci
      script:
        - docker run travis-ci /bin/bash -c "./scripts/build.py -t"

    - os: osx
      language: generic
      osx_image: xcode9
      install:
        - brew update
        - brew install boost cmake ninja
      script:
        - ./scripts/build.py -t
